name: cppcheck-action

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  workflow_dispatch:
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run script
      run: (cd ./build/ && ./perform_cppcheck.sh && cd ../)

    - uses: actions/upload-artifact@v4
      with:
        name: artifacts_cppcheck_html
        path: ./build/dir_cppcheck_html/
