# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name:  MSWindows_x86_64_MSBuild_WxNew

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  workflow_dispatch:
    branches: '*'

env:
  BUILD_CONFIGURATION: Release
  BUILD_TYPE: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2025

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Clone and bootstrap vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat

    - name: Install dependencies using vcpkg
      run: |
        .\vcpkg\vcpkg.exe install libarchive:x64-windows xapian:x64-windows
        echo "VCPKG_ROOT=${{ github.workspace }}\\vcpkg" >> $env:GITHUB_ENV

    - name: Install boost
      uses: MarkusJx/install-boost@v2.4.5
      id: install-boost
      with:
      # REQUIRED: Specify the required boost version
      # A list of supported versions can be found here:
      # https://github.com/MarkusJx/prebuilt-boost/blob/main/versions-manifest.json
          boost_version: 1.87.0
          toolset: msvc
          architecture: x64

    - name: Execute CMake
      run: cd build && cmd /c "set WXWIN=%cd%\..\3rdParty\wxWidgets\mswin_msvc_x86_64 && cmMSWindows_x86_64.bat" && cd ..
      env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}

    - name: Run MSBuild
      run: |
        cd build\Win && msbuild paperkernelcxx.sln /p:Configuration=Release /p:Platform=x64 /m && cd ..\..
        copy 3rdParty\wxWidgets\mswin_msvc_x86_64\lib\vc_x64_dll\*.dll build\bin\Release
        copy all_cxx_papers_individual_zst.tar build\bin\Release
        copy database_xapian_for_all_cxx_papers build\bin\Release
        Move-Item -Path build\bin\Release\main_program.exe -Destination build\bin\Release\paperkernelcxx.exe
        copy licenses\* build\bin\Release

    - uses: actions/upload-artifact@v4
      with:
        name: artifacts_MSWindows_x86_64_MSBuild_WxNew
        path: build/bin/Release/
